"""Re-export shim — canonical implementation lives in icecode.agent.curator."""
from icecode.agent.curator import (  # noqa: F401
    load_state,
    save_state,
    set_paused,
    is_paused,
    is_enabled,
    get_interval_hours,
    get_min_idle_hours,
    get_stale_after_days,
    get_archive_after_days,
    should_run_now,
    apply_automatic_transitions,
    run_curator_review,
    maybe_run_curator,
    CURATOR_DRY_RUN_BANNER,
    CURATOR_REVIEW_PROMPT,
    DEFAULT_INTERVAL_HOURS,
    DEFAULT_MIN_IDLE_HOURS,
    DEFAULT_STALE_AFTER_DAYS,
    DEFAULT_ARCHIVE_AFTER_DAYS,
)
